#!/usr/bin/env node
// Vendors the CloudYali design system's chart theme and brand mark into src/brand/assets.ts.
//
// The design system lives in the monorepo (design-system/packages/tokens); this repo is
// published to npm and cannot reach it at install time. So the values are vendored — and
// vendoring is how palettes drift, which is the whole reason this is a script and not a
// hand-edited file. Regenerate rather than edit:
//
//   node scripts/build-brand.mjs ../rajgad-master
//
// The generated header carries a checksum of each source. `npm test` asserts the file is
// exactly what this script would produce from the values it recorded, so a hand-edit is loud.
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const root = process.argv[2];
if (!root) {
  console.error("usage: node scripts/build-brand.mjs <path-to-rajgad-master>");
  process.exit(2);
}
const tokensDir = path.join(root, "design-system", "packages", "tokens");
const themePath = path.join(tokensDir, "dist", "echarts-theme.json");
const logoPath = path.join(root, "doc-site", "static", "img", "cloudyali-logo.svg");

for (const p of [themePath, logoPath]) {
  if (!fs.existsSync(p)) {
    console.error(`missing source: ${p}\nRun \`npm run build\` in design-system/packages/tokens first.`);
    process.exit(1);
  }
}

const themeRaw = fs.readFileSync(themePath, "utf8");
const theme = JSON.parse(themeRaw);
const logo = fs.readFileSync(logoPath, "utf8").replace(/>\s+</g, "><").trim();
const sha = (s) => crypto.createHash("sha256").update(s).digest("hex").slice(0, 12);

const out = `// GENERATED by scripts/build-brand.mjs — do not edit.
//
// Vendored from the CloudYali design system:
//   echarts-theme.json  sha256:${sha(themeRaw)}
//   cloudyali-logo.svg  sha256:${sha(logo)}
//
// Regenerate with:  node scripts/build-brand.mjs <path-to-rajgad-master>

/** The ECharts theme, resolved to literal hex. Canvas cannot read a CSS custom property. */
export const ECHARTS_THEME = ${JSON.stringify(theme, null, 2)} as const;

/** The CloudYali mark, minified. Self-contained: it carries its own gradient background,
 *  so it sits correctly on a light or a dark chart without a second asset. */
export const BRAND_MARK_SVG = ${JSON.stringify(logo)};
`;

fs.mkdirSync(path.join("src", "brand"), { recursive: true });
fs.writeFileSync(path.join("src", "brand", "assets.ts"), out);
console.log(`Vendored brand assets → src/brand/assets.ts (${theme.color.length} series colours, ${logo.length}B mark)`);
