import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { BRAND_MARK_SVG, ECHARTS_THEME } from "./assets.js";

// assets.ts is vendored from the monorepo's design system, and vendoring is how palettes drift.
// The generator records a checksum of each source in the file header; these tests check the
// vendored VALUES still hash to those recorded sums, so a hand-edit to the palette — the exact
// thing that would put the MCP's charts a shade off the console's — fails here instead of
// shipping.

const header = readFileSync(new URL("./assets.ts", import.meta.url), "utf8").slice(0, 600);
const sumFor = (label: string) => header.match(new RegExp(`${label}\\s+sha256:([0-9a-f]{12})`))?.[1];
const sha12 = (s: string) => createHash("sha256").update(s).digest("hex").slice(0, 12);

describe("vendored brand assets", () => {
  it("records where each asset came from", () => {
    expect(header).toMatch(/GENERATED by scripts\/build-brand\.mjs/);
    expect(sumFor("echarts-theme\\.json")).toMatch(/^[0-9a-f]{12}$/);
    expect(sumFor("cloudyali-logo\\.svg")).toMatch(/^[0-9a-f]{12}$/);
  });

  it("still matches the checksum of the mark it was generated from", () => {
    expect(sha12(BRAND_MARK_SVG)).toBe(sumFor("cloudyali-logo\\.svg"));
  });

  it("still matches the checksum of the theme it was generated from", () => {
    // The generator hashes the source file's exact bytes, which were pretty-printed with a
    // trailing newline by the design system's own build.
    expect(sha12(JSON.stringify(ECHARTS_THEME, null, 2) + "\n")).toBe(sumFor("echarts-theme\\.json"));
  });
});

describe("the theme is usable by ECharts as-is", () => {
  it("rotates exactly six literal colours", () => {
    expect(ECHARTS_THEME.color).toHaveLength(6);
    for (const c of ECHARTS_THEME.color) expect(c).toMatch(/^#[0-9a-f]{6}$/);
  });

  it("keeps the reserved roles out of the rotation", () => {
    // Every one of these means something. If ECharts hands `increase` to the fourth service in a
    // breakdown, the chart says that service is over budget.
    const { other, increase, decrease, warning, forecast } = ECHARTS_THEME.cloudyali;
    for (const [name, hex] of Object.entries({ other, increase, decrease, warning, forecast })) {
      expect(ECHARTS_THEME.color as readonly string[], `${name} leaked into the series ramp`).not.toContain(hex);
    }
  });

  it("gives increase and decrease colours a colour-blind reader can tell apart", () => {
    // Not red/green: under deuteranopia that pair is the one that collapses. Cheap proxy for the
    // full simulation the design system runs — assert the blue channels diverge sharply, which
    // red/green cannot do and red/teal does.
    const blue = (h: string) => parseInt(h.slice(5, 7), 16);
    const { increase, decrease } = ECHARTS_THEME.cloudyali;
    expect(Math.abs(blue(increase) - blue(decrease))).toBeGreaterThan(100);
  });

  it("orders the sequential ramp light to dark, so a heatmap reads in one direction", () => {
    const lum = (h: string) =>
      [1, 3, 5].reduce((n, i, k) => n + parseInt(h.slice(i, i + 2), 16) * [0.2126, 0.7152, 0.0722][k], 0);
    const ramp = ECHARTS_THEME.cloudyali.sequential.map(lum);
    for (let i = 1; i < ramp.length; i++) expect(ramp[i], `step ${i + 1}`).toBeLessThan(ramp[i - 1]);
  });

  it("carries a self-contained mark, with no asset an artifact cannot fetch", () => {
    expect(BRAND_MARK_SVG.startsWith("<svg")).toBe(true);
    expect(BRAND_MARK_SVG).not.toMatch(/<image|xlink:href|url\(['"]?http/);
    expect(BRAND_MARK_SVG.length).toBeLessThan(8000);
  });
});
